const locations={
  '95123':{name:'San Jose, California',county:'Santa Clara County',home:1180400,rent:2710,property:9840,hud:3140},
  '78701':{name:'Austin, Texas',county:'Travis County',home:629800,rent:1935,property:10210,hud:1967},
  '10001':{name:'New York, New York',county:'New York County',home:1045300,rent:2525,property:8860,hud:2940},
  '33101':{name:'Miami, Florida',county:'Miami-Dade County',home:518700,rent:1805,property:5330,hud:2260}
};
const rules={
  single:{deduction:16100,brackets:[[12400,.10],[50400,.12],[105700,.22],[201775,.24],[256225,.32],[640600,.35],[Infinity,.37]]},
  married:{deduction:32200,brackets:[[24800,.10],[100800,.12],[211400,.22],[403550,.24],[512450,.32],[768700,.35],[Infinity,.37]]},
  head:{deduction:24150,brackets:[[17700,.10],[67450,.12],[105700,.22],[201750,.24],[256200,.32],[640600,.35],[Infinity,.37]]}
};
let currentZip='95123';
const money=value=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(value);
function federalTax(income,status){const rule=rules[status],taxable=Math.max(0,income-rule.deduction);let tax=0,previous=0;for(const [ceiling,rate] of rule.brackets){const amount=Math.max(0,Math.min(taxable,ceiling)-previous);tax+=amount*rate;if(taxable<=ceiling)break;previous=ceiling}return tax}
function updateTax(){const income=Number(document.querySelector('#income').value)||0,status=document.querySelector('#filing-status').value,tax=federalTax(income,status),rate=income?tax/income*100:0;document.querySelector('#federal-tax').textContent=money(tax);document.querySelector('#federal-row').textContent=money(tax);document.querySelector('#effective-rate').textContent=`${rate.toFixed(1)}% effective rate`;document.querySelector('#tax-ring span').textContent=`${rate.toFixed(1)}%`;document.querySelector('#tax-ring').style.setProperty('--rate',`${Math.min(rate,100)*3.6}deg`)}
function showLocation(zip){const item=locations[zip];if(!item)return false;currentZip=zip;document.querySelector('#location-name').textContent=item.name;document.querySelector('#location-meta').textContent=`ZIP Code Tabulation Area ${zip} · ${item.county}`;document.querySelector('#home-value').textContent=money(item.home);document.querySelector('#median-rent').textContent=money(item.rent);document.querySelector('#property-tax').textContent=money(item.property);document.querySelector('#hud-rent').textContent=money(item.hud);document.querySelector('#snapshot').scrollIntoView({behavior:'smooth'});return true}
function difference(value,base){const change=value-base,percent=base?Math.abs(change/base*100):0;if(!change)return `<span class="difference same"><i aria-hidden="true">—</i><span><b>No difference</b><small>Same value</small></span></span>`;const direction=change>0?'higher':'lower',arrow=change>0?'↑':'↓';return `<span class="difference ${direction}"><i aria-hidden="true">${arrow}</i><span><b>${percent.toFixed(1)}% ${direction}</b><small>than current</small></span></span>`}
function comparisonRow(label,currentValue,targetValue,suffix=''){return `<div class="comparison-row"><div class="metric-label">${label}</div><div class="place-value current"><small>Current</small><strong>${money(currentValue)}</strong>${suffix?`<span>${suffix}</span>`:''}</div><div class="place-value target"><small>Compared</small><strong>${money(targetValue)}</strong>${suffix?`<span>${suffix}</span>`:''}</div>${difference(targetValue,currentValue)}</div>`}
function compareLocations(){const targetZip=document.querySelector('#compare-location').value,results=document.querySelector('#comparison-results'),current=locations[currentZip],target=locations[targetZip],income=Number(document.querySelector('#income').value)||0,status=document.querySelector('#filing-status').value,tax=federalTax(income,status),afterTax=income-tax;if(targetZip===currentZip){results.innerHTML='<p class="comparison-message">Choose a location different from your current snapshot.</p>';results.hidden=false;return}results.innerHTML=`<div class="comparison-summary"><div><span>Location comparison</span><p>Each arrow describes the compared location relative to your current location.</p></div><p>Based on ${money(income)} household income. State and local income taxes are not included yet.</p></div><div class="comparison-table"><div class="comparison-places"><div><small>Current location</small><strong>${current.name}</strong><span>${currentZip} · ${current.county}</span></div><div class="versus">VS</div><div><small>Compared location</small><strong>${target.name}</strong><span>${targetZip} · ${target.county}</span></div></div>${comparisonRow('Median home value',current.home,target.home)}${comparisonRow('Median gross rent',current.rent,target.rent,'per month')}${comparisonRow('Typical property tax paid',current.property,target.property,'per year')}<div class="comparison-row federal-row"><div class="metric-label">Federal income-tax estimate</div><div class="place-value current"><small>Current</small><strong>${money(tax)}</strong><span>per year</span></div><div class="place-value target"><small>Compared</small><strong>${money(tax)}</strong><span>per year</span></div><span class="difference same"><i aria-hidden="true">—</i><span><b>Same estimate</b><small>Federal rules do not change</small></span></span></div><div class="comparison-footnote"><b>After estimated federal tax: ${money(afterTax)}</b><span>This will become location-specific when verified state and local tax coverage is added.</span></div></div>`;results.hidden=false;results.scrollIntoView({behavior:'smooth',block:'nearest'})}
document.querySelector('#location-form').onsubmit=e=>{e.preventDefault();const zip=document.querySelector('#zip-input').value,toast=document.querySelector('#toast');if(!showLocation(zip)){toast.textContent='This prototype ZIP is not loaded yet. Try 95123, 78701, 10001, or 33101.';toast.hidden=false;setTimeout(()=>toast.hidden=true,4200)}};
document.querySelector('#tax-form').oninput=updateTax;
document.querySelector('#compare-button').onclick=compareLocations;
document.querySelector('#assembled-time').textContent=new Date().toLocaleDateString(undefined,{year:'numeric',month:'short',day:'numeric'});
updateTax();
