const placeLabels={
  '95123':{name:'San Jose, California',county:'Santa Clara County'},
  '78701':{name:'Austin, Texas',county:'Travis County'},
  '10001':{name:'New York, New York',county:'New York County'},
  '33101':{name:'Miami, Florida',county:'Miami-Dade County'}
};
const locations={};
const loadedPrefixes=new Map();
const loadedCityPrefixes=new Map();
const rules={
  single:{deduction:16100,brackets:[[12400,.10],[50400,.12],[105700,.22],[201775,.24],[256225,.32],[640600,.35],[Infinity,.37]]},
  married:{deduction:32200,brackets:[[24800,.10],[100800,.12],[211400,.22],[403550,.24],[512450,.32],[768700,.35],[Infinity,.37]]},
  head:{deduction:24150,brackets:[[17700,.10],[67450,.12],[105700,.22],[201750,.24],[256200,.32],[640600,.35],[Infinity,.37]]}
};
let currentZip=null;
const money=value=>value===null||value===undefined?'Not available':new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(value);
async function findLocation(zip){if(locations[zip])return locations[zip];const prefix=zip.slice(0,2);if(!loadedPrefixes.has(prefix)){loadedPrefixes.set(prefix,fetch(`data/zips/${prefix}.json`).then(response=>response.ok?response.json():[]).catch(()=>[]))}const records=await loadedPrefixes.get(prefix);for(const record of records){const label=placeLabels[record.zip];locations[record.zip]=label?{...record,...label}:record}return locations[zip]||null}
const normalizePlace=value=>value.toLowerCase().trim().replace(/\s+/g,' ');
async function findCities(query){const normalized=normalizePlace(query),prefix=normalized[0]?.replace(/[^a-z0-9]/,'_');if(!prefix)return[];if(!loadedCityPrefixes.has(prefix)){loadedCityPrefixes.set(prefix,fetch(`data/cities/${prefix}.json`).then(response=>response.ok?response.json():[]).catch(()=>[]))}const places=await loadedCityPrefixes.get(prefix);return places.filter(place=>place.normalized.startsWith(normalized)).slice(0,12)}
function showCityChoices(places){const results=document.querySelector('#search-results');if(!places.length){results.hidden=true;results.innerHTML='';return}results.innerHTML=`<strong>Select a ZIP area</strong>${places.map(place=>`<button type="button" data-zip="${place.zip}"><span>${place.label}</span><b>${place.zip}</b></button>`).join('')}`;results.hidden=false}
function federalTax(income,status){const rule=rules[status],taxable=Math.max(0,income-rule.deduction);let tax=0,previous=0;for(const [ceiling,rate] of rule.brackets){const amount=Math.max(0,Math.min(taxable,ceiling)-previous);tax+=amount*rate;if(taxable<=ceiling)break;previous=ceiling}return tax}
function updateTax(){const income=Number(document.querySelector('#income').value)||0,status=document.querySelector('#filing-status').value,tax=federalTax(income,status),rate=income?tax/income*100:0;document.querySelector('#federal-tax').textContent=money(tax);document.querySelector('#federal-row').textContent=money(tax);document.querySelector('#effective-rate').textContent=`${rate.toFixed(1)}% effective rate`;document.querySelector('#tax-ring span').textContent=`${rate.toFixed(1)}%`;document.querySelector('#tax-ring').style.setProperty('--rate',`${Math.min(rate,100)*3.6}deg`)}
async function showLocation(zip){const item=await findLocation(zip);if(!item)return false;currentZip=zip;document.querySelector('#search-results').hidden=true;document.querySelector('#zip-input').value=zip;document.querySelector('#location-name').textContent=item.name;document.querySelector('#location-meta').textContent=`ZIP Code Tabulation Area ${zip} · ${item.county}`;document.querySelector('#home-value').textContent=money(item.home);document.querySelector('#median-rent').textContent=money(item.rent);document.querySelector('#property-tax').textContent=money(item.property);document.querySelector('#property-rate').textContent=item.property!==null&&item.home?`${(item.property/item.home*100).toFixed(2)}%`:'Not available';document.querySelector('#hud-rent').textContent=money(item.hud);const censusYear=item.censusYear||2024;document.querySelector('#home-year').textContent=`${censusYear} data`;document.querySelector('#rent-year').textContent=`${censusYear} data`;document.querySelector('#property-year').textContent=`${censusYear} data`;document.querySelector('#hud-year').textContent=item.hud?`FY 2026`:'Coverage pending';document.querySelector('#snapshot').hidden=false;document.querySelector('#compare').hidden=false;document.querySelector('#comparison-results').hidden=true;document.querySelector('#snapshot').scrollIntoView({behavior:'smooth'});return true}
function clearLocation(){currentZip=null;document.querySelector('#location-form').reset();document.querySelector('#search-results').hidden=true;document.querySelector('#location-name').textContent='';document.querySelector('#location-meta').textContent='';document.querySelector('#snapshot').hidden=true;document.querySelector('#compare').hidden=true;const results=document.querySelector('#comparison-results');results.hidden=true;results.innerHTML='';document.querySelector('#top').scrollIntoView({behavior:'smooth'});setTimeout(()=>document.querySelector('#zip-input').focus(),450)}
function difference(value,base){if(value===null||base===null)return `<span class="difference same"><i aria-hidden="true">—</i><span><b>Unavailable</b><small>Cannot compare</small></span></span>`;const change=value-base,percent=base?Math.abs(change/base*100):0;if(!change)return `<span class="difference same"><i aria-hidden="true">—</i><span><b>No difference</b><small>Same value</small></span></span>`;const direction=change>0?'higher':'lower',arrow=change>0?'↑':'↓';return `<span class="difference ${direction}"><i aria-hidden="true">${arrow}</i><span><b>${percent.toFixed(1)}% ${direction}</b><small>than current</small></span></span>`}
function comparisonRow(label,currentValue,targetValue,suffix=''){return `<div class="comparison-row"><div class="metric-label">${label}</div><div class="place-value current"><small>Current</small><strong>${money(currentValue)}</strong>${suffix?`<span>${suffix}</span>`:''}</div><div class="place-value target"><small>Compared</small><strong>${money(targetValue)}</strong>${suffix?`<span>${suffix}</span>`:''}</div>${difference(targetValue,currentValue)}</div>`}
async function compareLocations(){const targetZip=document.querySelector('#compare-location').value,results=document.querySelector('#comparison-results'),current=await findLocation(currentZip),target=await findLocation(targetZip),income=Number(document.querySelector('#income').value)||0,status=document.querySelector('#filing-status').value,tax=federalTax(income,status),afterTax=income-tax;if(targetZip===currentZip){results.innerHTML='<p class="comparison-message">Choose a location different from your current snapshot.</p>';results.hidden=false;return}results.innerHTML=`<div class="comparison-summary"><div><span>Location comparison</span><p>Each arrow describes the compared location relative to your current location.</p></div><p>Based on ${money(income)} household income. State and local income taxes are not included yet.</p></div><div class="comparison-table"><div class="comparison-places"><div><small>Current location</small><strong>${current.name}</strong><span>${currentZip} · ${current.county}</span></div><div class="versus">VS</div><div><small>Compared location</small><strong>${target.name}</strong><span>${targetZip} · ${target.county}</span></div></div>${comparisonRow('Median home value',current.home,target.home)}${comparisonRow('Median gross rent',current.rent,target.rent,'per month')}${comparisonRow('Typical property tax paid',current.property,target.property,'per year')}<div class="comparison-row federal-row"><div class="metric-label">Federal income-tax estimate</div><div class="place-value current"><small>Current</small><strong>${money(tax)}</strong><span>per year</span></div><div class="place-value target"><small>Compared</small><strong>${money(tax)}</strong><span>per year</span></div><span class="difference same"><i aria-hidden="true">—</i><span><b>Same estimate</b><small>Federal rules do not change</small></span></span></div><div class="comparison-footnote"><b>After estimated federal tax: ${money(afterTax)}</b><span>This will become location-specific when verified state and local tax coverage is added.</span></div></div>`;results.hidden=false;results.scrollIntoView({behavior:'smooth',block:'nearest'})}
document.querySelector('#location-form').onsubmit=async e=>{e.preventDefault();const query=document.querySelector('#zip-input').value.trim(),toast=document.querySelector('#toast'),button=e.currentTarget.querySelector('button');button.disabled=true;button.textContent='Loading…';if(/^\d{5}$/.test(query)){if(!await showLocation(query)){toast.textContent='No Census residential ZIP-area record was found for that ZIP code.';toast.hidden=false;setTimeout(()=>toast.hidden=true,4200)}}else{const places=await findCities(query);showCityChoices(places);if(!places.length){toast.textContent='No matching city was found. Try “City, ST” or a five-digit ZIP.';toast.hidden=false;setTimeout(()=>toast.hidden=true,4200)}}button.disabled=false;button.textContent='Build my snapshot'};
document.querySelector('#search-results').onclick=async e=>{const choice=e.target.closest('[data-zip]');if(choice)await showLocation(choice.dataset.zip)};
document.querySelector('#tax-form').oninput=updateTax;
document.querySelector('#compare-button').onclick=compareLocations;
document.querySelector('#clear-location').onclick=clearLocation;
fetch('data/metadata.json').then(response=>response.ok?response.json():null).then(metadata=>{document.querySelector('#assembled-time').textContent=metadata?.refreshedAt?new Date(metadata.refreshedAt).toLocaleString(undefined,{year:'numeric',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'Prototype data'}).catch(()=>document.querySelector('#assembled-time').textContent='Prototype data');
updateTax();
